apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: artifactory-proxy
  name: artifactory-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: artifactory-proxy
    spec:
      containers:
      - env:
        - name: CODEARTIFACT_DOMAIN
          value: ""
        - name: CODEARTIFACT_REPO
          value: ""
        - name: CODEARTIFACT_OWNER
          value: ""
        - name: CODEARTIFACT_TYPE
          value: ""
        - name: AWS_REGION
          value: ""
        image: image
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 5
        name: artifactory-proxy
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
        resources:
          limits:
            memory: 20Mi
          requests:
            cpu: 5m
            memory: 10Mi
      terminationGracePeriodSeconds: 30
