piVersion: v1
kind: Service
metadata:
  labels:
    app: artifactory-proxy
  name: artifactory-proxy
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: artifactory-proxy
  type: ClusterIP